services:
    kismet:
        container_name: kismet
        image: dciancu/kismet-wireless-docker:stable
        init: true
        privileged: true
        network_mode: host
        restart: unless-stopped
        volumes:
            #- ./storage/conf:/usr/local/etc
            - ./storage/custom-conf:/mnt/custom-conf
            - ./storage/data:/home/kismet
